paths:
  medicaid_updates: data/raw/Childrens Evolution of Care/State/Medicaid Updates
  children_waiver: data/raw/Childrens Evolution of Care/State/Waivers/Childrens Waiver
  processed: data/processed/medicaid update
  chunked: data/chunks

input_patterns: ["*.pdf", "*.docx", "*.doc"]
